#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 20:24:50 2020

@author: callumwilliams
"""

import numpy as np
import scipy as sp

 
c = 3e8
c_nat = 1

m_pi_m = 140 #MeV
m_K_m = 490 #MeV
m_m_m= 105 #MeV
m_n = 500 #eV

m_n_m = 5e-4

m_pi_g = 0.14 #GeV
m_K_g = 0.49 #GeV
m_m_g = 0.105 #GeV
m_n_g = 5e-7 #GeV


#Functions

def E_c(m_a,m_b,m_c): 
    E_c = (m_a**2+m_b**2-m_c**2)/(2*m_a)
    return E_c #units eV/c^2

def momentum(E,m):
    p = np.sqrt((E**2 - m**2))
    return p

def three_momentum(p,phi,theta):
    px = p*np.sin(theta)*np.cos(phi)
    py = p*np.sin(theta)*np.sin(phi)
    pz = p*np.cos(theta)
    return np.array([px,py,pz])

def four_momentum(E,three_momentum):
    four_momentum = np.array([E, three_momentum[0], three_momentum[1], three_momentum[2]])
    return four_momentum

def beta(E,m):
    beta = np.sqrt(1-(m/E)**2)
    return beta

def boosted_fourmomentum(four_momentum, beta):
    y = (1-beta**2)**0.5
    transmatrix = [[y,0,0,-1*y*beta],[0,1,0,0],[0,0,1,0],[-1*y*beta,0,0,y]]
    boosted_fourmomentum = np.matmul(transmatrix,four_momentum)
    return boosted_fourmomentum

def find4mtm_c_lf(mA,mB,mC,theta,phi,EA):
    Ec_rf = (mA**2-mB**2+mC**2)/(2*mA)
    three_mom = three_momentum((EA**2-mA**2)**0.5,theta,phi)
    mtm = [Ec_rf, three_mom[0], three_mom[1], three_mom[2]]
    return mtm


#%%
print('Section 1')

#%%
print('Section 1.1')

#%%
print('Section 1.2')
    
Enu_rf_pi_g = E_c(m_pi_g,m_n_g,m_m_g)
print('The neutrino produced in the pion decay is: ',Enu_rf_pi_g,'GeV/c^2')

Enu_rf_K_g = E_c(m_K_g,m_n_g,m_m_g)
print('The neutrino produced in the Kaon decay is: ',Enu_rf_K_g,'GeV/c^2')

#%%
print('Section 1.3')

p_neutrino_pi_decay = (Enu_rf_pi_g**2 - m_n_g**2)**0.5
print(p_neutrino_pi_decay)
p_neutrino_K_decay = (Enu_rf_K_g**2 - m_n_g**2)**0.5
print(p_neutrino_K_decay)

three_momentum_pi = three_momentum(p_neutrino_pi_decay, (np.pi)/2, (np.pi)/6)
print('The three momentum of the neutrino from the pion decay is: ',three_momentum_pi)

three_momentum_K = three_momentum(p_neutrino_K_decay, (np.pi)/2, (np.pi)/6)
print('The three momentum of the neutrino from the K decay is: ',three_momentum_K)

#%%
print('Section 1.4')


#%%
print('Section 1.5')

#%%
print('Section 2')
    
#%%
print('Section 2.1')

#%%
print('Section 2.2')

#%%
print('Section 2.3')
    
beta_pi = beta(1, m_pi_g)*(-1) #when converting from rest from to lab frame, v in the +z direction, so backwards is -z
print(beta_pi)

beta_K = beta(1, m_K_g)*(-1)
print(beta_K)

#%%
print('Section 2.4')

enu_pion = Enu_rf_pi_g
enu_kaion = Enu_rf_K_g

four_mom_n_pi = four_momentum(enu_pion,three_momentum_pi)
four_mom_n_K = four_momentum(enu_kaion,three_momentum_K)

print("In the lab frame the four momentum of both the pion and kaion respectivly are:",four_mom_n_pi,four_mom_n_K)

lt_four_mom_n_pi = boosted_fourmomentum(four_mom_n_pi,beta_pi)
lt_four_mom_n_K = boosted_fourmomentum(four_mom_n_K,beta_K)

print("The boosted four momentum of both the pion and kaion respectivly are:",lt_four_mom_n_pi,lt_four_mom_n_K)

#%%
print('Section 2.5')

print(find4mtm_c_lf(m_pi_m,m_m_g,m_n_m,(np.pi)/2,(np.pi)/6,1*1000))

four_mom_mu_pi_lf = find4mtm_c_lf(m_pi_m,m_n_m,m_m_m, np.pi/2,np.pi/6,1*1000)
four_mom_mu_K_lf = find4mtm_c_lf(m_K_m,m_n_m,m_m_m, np.pi/2,np.pi/6,1*1000)

four_mom_n_pi_lf = find4mtm_c_lf(m_pi_m,m_m_m,m_n_m, np.pi/2,np.pi/6,1*1000)
four_mom_n_K_lf = find4mtm_c_lf(m_K_m,m_m_m,m_n_m, np.pi/2,np.pi/6,1*1000)

#%%
print('Section 2.6')

mom_muon_pi_lf = find4mtm_c_lf(m_pi_m,m_n_m,m_m_m, np.pi/2,np.pi/6, 1*1000)
mom_muon_K_lf = find4mtm_c_lf(m_K_m,m_n_m,m_m_m, np.pi/2,np.pi/6, 1*1000)

E_mu_pi = E_c(m_pi_g,m_n_g,m_m_g)
E_mu_K = E_c(m_K_g,m_n_g,m_m_g)

mom_mu_pi = (E_mu_pi**2 - m_m_g**2)
mom_mu_K = (E_mu_K**2 - m_m_g**2)

#print(mom_mu_pi)

three_mom_mu_pi = three_momentum(mom_mu_pi, sp.pi/2, sp.pi/6)
three_mom_mu_K = three_momentum(mom_mu_K, sp.pi/2, sp.pi/6)

#print(three_mom_mu_k)

four_mom_mu_pi = four_momentum(E_mu_pi, three_mom_mu_pi)
four_mom_mu_K = four_momentum(E_mu_K, three_mom_mu_K)

#print(four_mom_mu_pi)

#difference = lab frame = rest frame

diff_four_mom_mu_pi = four_mom_mu_pi - four_mom_mu_pi_lf
print('difference between rest frame and lab frame for muon in pi decay: ',diff_four_mom_mu_pi) 

diff_four_mom_mu_K = four_mom_mu_K - four_mom_mu_K_lf
print('difference between rest frame and lab frame for muon in k decay: ',diff_four_mom_mu_K)

diff_four_mom_n_pi = four_mom_n_pi - four_mom_n_pi_lf
print('difference between rest frame and lab frame for neutrino in pi decay: ',diff_four_mom_n_pi) 

diff_four_mom_n_K = four_mom_n_K - four_mom_n_K_lf
print('difference between rest frame and lab frame for neutrino in k decay: ',diff_four_mom_n_K)

#%%
print('Section 2.7')

angle_min = np.pi
angle_max = 0
phi = sp.pi/6

Enu_lf_pi_min = ((find4mtm_c_lf(m_pi_g,m_n_g,m_m_g,angle_min,phi,1))[0]) 
Enu_lf_pi_max = ((find4mtm_c_lf(m_pi_g,m_n_g,m_m_g,angle_max,phi,1))[0])

Enu_lf_K_min = ((find4mtm_c_lf(m_K_g,m_n_g,m_m_g,angle_min,phi,1))[0]) 
Enu_lf_K_max = ((find4mtm_c_lf(m_K_g,m_n_g,m_m_g,angle_max,phi,1))[0])

print('the min energy for the product neutrino for the pion decay is: ', Enu_lf_pi_min, 'GeV')
print('the max energy for the product neutrino for the pion decay is: ', Enu_lf_pi_max, 'GeV')

print('the min energy for the product neutrino for the kaon decay is: ', Enu_lf_K_min, 'GeV')
print('the max energy for the product neutrino for the kaon decay is: ', Enu_lf_K_max, 'GeV')

#%%
print('Section 3')
#The allowed values between 0 and 2pi
#%%
print('Section 3.1')

print(np.random.rand())









